<a href="https://colab.research.google.com/github/SargoHub/pythonPractice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY LIBRARY


In [6]:
# importing the library
import numpy as np   # np is created as a alias so that calling the fucntion becomes easier


In [8]:
l=[1,34,56,2]
#creating the numpy one directional array from the list
a=np.array(l)
a


array([ 1, 34, 56,  2])

In [12]:
# multi dimensional array
# first creating a one dimensional array
x=np.array([1,67,28,47])
x

array([ 1, 67, 28, 47])

In [16]:
print(x.ndim)  # this gives the dimension of the array
print(x.shape) # gives the number of elements present in the array
print(x.dtype)  # will tell the data type in the array

1
(4,)
int64


In [22]:
# 2 dimensional array
s=np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
print(s.ndim)
print(s.shape)   # gives the number of (rows,cloumns)

2
(2, 3)


In [25]:
s.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
print(p.ndim)
print(p.shape)
print(p.size)

3
(2, 2, 3)
12


In [32]:
g=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(g.size)
print(g.ndim)
g.reshape(2,6)
g.reshape(4,3)


12
1


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
# 3 dimensional array
p=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
p  # this array has one 3 dimensional, two 2-dimensional inside it, and two 1-dimensional inside the 2-dimensional

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
t=np.array([[[1,2,3],[4,5,6]]])
print(t[0])  # gives the 2-dimensional array present in the 3-dimensional array
print(t[0][1])  # gives the second 1-dimensional array of the 2-dimensional
print(t[0][1][1]) # gives the second index value of the 1-dimensional array

[[1 2 3]
 [4 5 6]]
[4 5 6]
5


In [38]:
# ndmin to give the number of dimension of array
g=np.array([1,2,3,5],ndmin=4)  # to create a 4 dimension array using ndmin
g


array([[[[1, 2, 3, 5]]]])