<a href="https://colab.research.google.com/github/SargoHub/pythonPractice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY LIBRARY


In [ ]:
# importing the library
import numpy as np   # np is created as a alias so that calling the fucntion becomes easier


In [ ]:
l=[1,34,56,2]
#creating the numpy one directional array from the list
a=np.array(l)
a


array([ 1, 34, 56,  2])

In [ ]:
# multi dimensional array
# first creating a one dimensional array
x=np.array([1,67,28,47])
x

array([ 1, 67, 28, 47])

In [ ]:
print(x.ndim)  # this gives the dimension of the array
print(x.shape) # gives the number of elements present in the array
print(x.dtype)  # will tell the data type in the array

1
(4,)
int64


In [ ]:
# 2 dimensional array
s=np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(s.ndim)
print(s.shape)   # gives the number of (rows,cloumns)

2
(2, 3)


In [ ]:
s.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(p.ndim)
print(p.shape)
print(p.size)

3
(2, 2, 3)
12


In [ ]:
g=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(g.size)
print(g.ndim)
g.reshape(2,6)
g.reshape(4,3)


12
1


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# 3 dimensional array
p=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
p  # this array has one 3 dimensional, two 2-dimensional inside it, and two 1-dimensional inside the 2-dimensional

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
t=np.array([[[1,2,3],[4,5,6]]])
print(t[0])  # gives the 2-dimensional array present in the 3-dimensional array
print(t[0][1])  # gives the second 1-dimensional array of the 2-dimensional
print(t[0][1][1]) # gives the second index value of the 1-dimensional array

[[1 2 3]
 [4 5 6]]
[4 5 6]
5


In [ ]:
# ndmin to give the number of dimension of array
g=np.array([1,2,3,5],ndmin=4)  # to create a 4 dimension array using ndmin
g


array([[[[1, 2, 3, 5]]]])

In [2]:
import numpy as np
k=np.array([[4,8,7],[7,5,8]],ndmin=6)
k

array([[[[[[4, 8, 7],
           [7, 5, 8]]]]]])

In [8]:
#INDEXING AND SLICING
f=np.array([[1,2,3],[4,7,3]])
print(f[0][2])
print(f[1][0:2])




3
[4 7]


6

In [12]:
r=np.array([[[2,4]],[[4,5]]])
r.shape   # for a 3-dimensional array the shape gives (no. of 2 dimensional arrays, rows, columns)



(2, 1, 2)

In [13]:
# CONCATENATION OF NUMPY ARRAYS
a1=np.array([[1,5,9]])
a2=np.array([[7,5,3]])
s=np.concatenate((a1,a2))  # in the concatenate fucn pass the array to be concatenated as tuple (both array should be of same dimensions)
s


array([[1, 5, 9],
       [7, 5, 3]])

In [14]:
u1=np.array([4,5])
u2=np.array([7,8])
o=np.concatenate((u1,u2))
o

array([4, 5, 7, 8])

In [19]:
p1=np.array([[4,5]])
p2=np.array([[7,8]])
l=np.concatenate((p1,p2),axis=1)  # join the array in one line using axis=1 argument
l


array([[4, 5, 7, 8]])

In [22]:
# RANDOM FUNCTION
a=np.random.random(3)
a



array([0.12885463, 0.42343919, 0.5807534 ])

In [24]:
b=np.random.random((3,4))
b

array([[0.67540066, 0.12285521, 0.22623996, 0.19968425],
       [0.09612948, 0.33810419, 0.88310328, 0.37707781],
       [0.1609879 , 0.08701892, 0.81836643, 0.90855908]])

In [25]:
c=np.random.random((2,2,3))
c


array([[[0.74190736, 0.08035022, 0.19257715],
        [0.35651472, 0.3285753 , 0.04705584]],

       [[0.16408828, 0.97650368, 0.22745191],
        [0.98827334, 0.92604101, 0.52338843]]])

In [26]:
r=np.random.random(8).reshape(2,4)
r


array([[0.24489749, 0.16578122, 0.13103278, 0.25028852],
       [0.58967078, 0.26637615, 0.68568865, 0.82426842]])

In [28]:
# RANDINT Functions
h=np.random.randint(1,100,7)  # format is (start, end, size)
h


array([60, 61, 83, 48, 11, 12, 14])

In [30]:
v=np.random.randint(1,99)  # this will just give one random number every time b/w 1 and 99
v


25

In [34]:
# using the seed function to freeze the randomness
np.random.seed(1) # seed makes sure that now everytime we run the random function it does not give a new random output
j=np.random.randint(0,100,10)
j


array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])